src/Entity/OrderLine.php
<?php

namespace App\Entity;

use App\Repository\OrderLineRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=OrderLineRepository::class)
 * @UniqueEntity(fields={"idOrderLine"}, message="Commande déjà enregistré")
 */
class OrderLine
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $idOrder;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $idOrderLine;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float", length=255, nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="float", length=255, nullable=true)
     */
    private $priceUnit;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $remainingQtyOrder;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $idOrderX3;

    /**
     * @ORM\ManyToOne(targetEntity=Item::class, inversedBy="orderLines")
     */
    private $itemID;

    /**
     * @ORM\ManyToOne(targetEntity=OrderDraft::class, inversedBy="orderLines")
     */
    private $orderDraftID;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $promo;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdOrder(): ?int
    {
        return $this->idOrder;
    }

    public function setIdOrder(?int $idOrder): self
    {
        $this->idOrder = $idOrder;
        return $this;
    }

    public function getIdOrderLine(): ?int
    {
        return $this->idOrderLine;
    }

    public function setIdOrderLine(?int $idOrderLine): self
    {
        $this->idOrderLine = $idOrderLine;
        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getPriceUnit(): ?float
    {
        return $this->priceUnit;
    }

    public function setPriceUnit(?float $priceUnit): self
    {
        $this->priceUnit = $priceUnit;
        return $this;
    }

    public function getRemainingQtyOrder(): ?int
    {
        return $this->remainingQtyOrder;
    }

    public function setRemainingQtyOrder(?int $remainingQtyOrder): self
    {
        $this->remainingQtyOrder = $remainingQtyOrder;
        return $this;
    }

    public function getIdOrderX3(): ?int
    {
        return $this->idOrderX3;
    }

    public function setIdOrderX3(int $idOrderX3): self
    {
        $this->idOrderX3 = $idOrderX3;
        return $this;
    }

    public function getItemID()
    {
        return $this->itemID;
    }

    public function setItemID($itemID)
    {
        $this->itemID = $itemID;
        return $this;
    }

    public function getOrderDraftID(): ?OrderDraft
    {
        return $this->orderDraftID;
    }

    public function setOrderDraftID(?OrderDraft $orderDraftID): self
    {
        $this->orderDraftID = $orderDraftID;

        return $this;
    }

    public function getPromo(): ?bool
    {
        return $this->promo;
    }

    public function setPromo(?bool $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getDiscount1(): int {
        return 0;
    }

    public function getDiscountedPrice() {
        return $this->getPrice() * (1 - $this->getDiscount1());
    }

    public function getGratuityCode() {
        return '';
    }

    public function getCode() {
        return '';
    }

    public function getIdItem() {
        return $this->getItemID();
    }

    public function quantityBundling() {
        return $this->getItemID()->getAmountBulking();
    }

    public function getUniqueId()
    {
        return $this->getIdOrderLine();
    }
}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Form\CsvOrderUploaderType;
use App\Form\OrderType;
use App\Repository\OrderDraftRepository;
use App\Services\Cart\CartItem;
use App\Services\ItemServices;
use App\Services\OrderServices;
use App\Services\PromoServices;
use App\Services\ShopServices;
use Exception;
use League\Csv\Reader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class ShopController extends AbstractController
{
    /**
     * @Route("/{_locale}/panier", name="app_shop", requirements={"_locale"="%app.locales%"})
     */
    public function index(ShopServices $shopServices, CartItem $cartItem, Request $request, SluggerInterface $slugger, ItemServices $itemService): Response
    {
        $society = $this->getUser()->getSocietyID();
        $freeRestockingRules = $shopServices->getFreeRestockingRules($society);
        $errors = [];

        $form = $this->createForm(CsvOrderUploaderType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $file = $form->get('update_csv_order')->getData();

            if ($file) {
                if($file->getClientOriginalExtension() !== 'csv'){
                    $errors[] = "You have entered an invalid file, try a file with '.csv' extension";
                } else {
                    $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    // this is needed to safely include the file name as part of the URL
                    $safeFilename = $slugger->slug($originalFilename);

                    $newFilename = $safeFilename.'-'.uniqid(). '.' . $file->getClientOriginalExtension();

                    try {
                        $file->move(
                            $this->getParameter('upload_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        $errors[] = "Something went wrong while uploading file, try again !";
                    }

                    $csv = Reader::createFromPath($this->getParameter('upload_directory') . '/' . $newFilename, 'r');
                    if(str_contains($csv->toString(),';')){
                        $csv->setDelimiter(';');
                    }
                    $records = $csv->getRecords();
                    try {
                        foreach($records as $row){
                            $item = $itemService->getItemByX3Id($row[0]);
                            $shopServices->addToCart($society, $item->getId(), $row[1], 0);
                        }
                    } catch(Exception $e) {
                        $errors[] = "We have no item with this id : " . $row[0];
                    }
                }
            }
        }

        $orders  = $shopServices->getOrderDraft($society);

        return $this->render('shop/index.html.twig', [
            'controller_name' => 'ShopController',
            'orders'          => $orders,
            'cartItem'        => $cartItem->getItemCart($society->getId()),
            'form'            => $form->createView(),
            'errors'          => $errors,
            'freeRestockingRules' => $freeRestockingRules
        ]);
    }

    /**
     *  @Route("/{_locale}/promo", name="app_promo_shop", requirements={"_locale"="%app.locales%"})
     */
    public function panierPromo(ShopServices $shopServices, CartItem $cartItem, PromoServices $promoServices): Response
    {
        $society = $this->getUser()->getSocietyID();
        $orders = $shopServices->getOrderDraftPromo($society);
        $promo = $promoServices->getPromoSociety();

        return $this->render('shop/promo.html.twig', [
            'controller_name' => 'ShopController',
            'orders' => $orders,
            'cartItem' => $cartItem->getItemCart($society->getId()),
            'promos' => $promo
        ]);
    }

    /**
     * @Route("/{_locale}/order-publish/{promo}", name="app_order_publish")
     */
    public function orderPublish(CartItem $cartItem, Request $request, ShopServices $shopServices, TranslatorInterface $translator): Response
    {
        $society = $this->getUser()->getSocietyID();
        $form = $this->createForm(OrderType::class, null, [
            'societyId' => $society->getId(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $society = $this->getUser()->getSocietyID();

            $formData = $form->getData();
            $formData->setIdStatut(2);
            if(!empty($form->getExtraData()) && array_keys($form->getExtraData())[0] === 'saveDraft') {
                $formData->setIdStatut(1);
            }
            $order   = $shopServices->createOrder($this->getUser(), $society, $formData, $request->get('promo'));
            if ($order != null) {
                $this->addFlash($order['type'], $order['msg']);
                return $this->redirectToRoute('app_shop');
            }
            return $this->redirectToRoute('app_order');
        }

        $cartItem = $cartItem->getItemCart($society->getId());

        if ($cartItem == 0){
            $this->addFlash('error', $translator->trans('Panier vide'));
            return $this->redirectToRoute('app_shop');
        }

        return $this->render('shop/publish.html.twig', [
            'controller_name' => 'ShopController',
            'cartItem'        => $cartItem,
            'form'            => $form->createView(),
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @Route("/{_locale}/order-edit/{id}", name="app_order_edit")
     */
    public function orderEdit(
        Request $request,
        OrderServices $orderServices,
        CartItem $cartItem,
        ShopServices $shopServices
    ): Response
    {
        $society = $this->getUser()->getSocietyID();
        $freeRestockingRules = $shopServices->getFreeRestockingRules($society);

        $id = $request->get('id');
        $order = $orderServices->getOrderByID($id);
        $orderLines = $orderServices->getOrderLinesByID($id);

        $cartItemCount = 0;
        if($request->get('token') !== 'token') {
            $cartItemCount = $cartItem->getItemCart($this->getUser()->getSocietyID()->getId());
        }

        if($request->get('token') !== 'token' && ($order->getIdStatut() !== 1 || in_array('ROLE_ADMIN', $this->getUser()->getRoles()))) {
            return $this->redirectToRoute('app_order');
        }

        return $this->render('shop/edit.html.twig', [
            'controller_name' => 'ShopController',
            'order'           => $order,
            'orders'          => $orderLines,
            'cartItem'        => $cartItemCount,
            'form'            => null,
            'errors'          => [],
            'freeRestockingRules' => $freeRestockingRules,
        ]);
    }

    /**
     * @Route("/{_locale}/order-publish-edit/{id}", name="app_order_edit_publish")
     */
    public function orderEditPublish(Request $request, ShopServices $shopServices, OrderServices $orderServices): Response
    {

        $id = $request->get('id');
        $order = $orderServices->getOrderByID($id);

        $society = $this->getUser()->getSocietyID();
        $form = $this->createForm(OrderType::class, null, [
            'societyId' => $society->getId(),
        ]);
        $form->handleRequest($request);

        if(!$form->isSubmitted()) {
            $form->setData($order);
        }

        if ($form->isSubmitted() && $form->isValid()) {

            $formData = $form->getData();
            $formData->setIdStatut(2);
            if(!empty($form->getExtraData()) && array_keys($form->getExtraData())[0] === 'saveDraft') {
                $formData->setIdStatut(1);
            }

            $order = $shopServices->updateOrder($order, $form->getData());
            if ($order != null) {
                return $this->redirectToRoute('app_order');
            }
            return $this->redirectToRoute('app_order_edit', [
                'id' => $id,
            ]);
        }

        return $this->render('shop/publish.html.twig', [
            'controller_name' => 'ShopController',
            'form'            => $form->createView(),
            'user' => $this->getUser(),
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{_locale}/order-delete-item/{id}", name="app_order_product_delete")
     */
    public function orderDeleteItem(Request $request, ShopServices $shopServices, OrderDraftRepository $orderDraftRepository): Response
    {
        // TODO : Checker si la société est bien celle de la personne qui supprime le produit.
        $id = $request->get('id');
        $societyId = $this->getUser()->getSocietyID()->getId();
        $order = $orderDraftRepository->find($id);
        $shopServices->deleteItemOrderDraft($id);
        $shopServices->deleteFreeItem($societyId);

        if ($order->getPromo() == true) {
            return $this->redirectToRoute('app_promo_shop');
        }

        return $this->redirectToRoute('app_shop');
    }

/**
     * @Route("/add-to-order/{orderId}/{orderLineId}/{qty}", name="app_order_edit_quantity_item")
     */
    public function orderEditQuantityItem(Request $request, ShopServices $shopServices): Response
    {
        $orderId = $request->get('orderId');
        $orderLineId = $request->get('orderLineId');
        $quantity = $request->get('qty');

        $shopServices->updateQuantityOrderLineById($orderLineId, $quantity);

templates/shop/_total.html.twig
<table class="table-responsive cart--table-totals">
    <tbody>
    <tr class="cart-subtotal">
        <th>{{ 'Subtotal' | trans }}</th>
        <td>
            <span class="price total" id="priceTotal">{{ subtotal }} €</span>
        </td>
    </tr>
    <tr class="cart-gratuity">
        <th>{{ 'gratuity' | trans }}</th>
        <td>
            <span class="price total" id="priceTotal">{{ gratuity }} €</span>
        </td>
    </tr>
    <tr class="order-total">
        <th>{{ 'Total'| trans }} </th>
        <td>
            <span class="price total" id="priceTotal">{{ total }} €</span>
        </td>
    </tr>
    </tbody>
</table>

templates/shop/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'my_cart' | trans }}
{% endblock %}

{% block body %}
    <section class="section section--checkout">
        <div class="container">
            <form action="#">
                <div class="row">
                    <div class="col-12 col-md-8">
                        {% include 'flash_messages.html.twig' %}

                        <div class="cart--checkout-table">
                            <div class="search-wrapper" style="display:flex">
                                <input class="js-cart-search-term" type="text" style="outline:none" />
                                <button class="button button--primary-fill js-cart-search-button">
                                    {{ 'search.product' | trans}}
                                </button>
                            </div>
                            <div class="search-results"></div>
                            <br />
                            <table class="cart--table table-responsive">
                                <thead>
                                    <tr>
                                        <th>{{'Product' | trans}}</th>
                                        <th>{{'Designation' | trans}}</th>
                                        <th>{{'quantity' | trans}}</th>
                                        <th>{{'Quantity.counts' | trans}}</th>
                                        <th>{{'price.unit' | trans}}</th>
                                        <th>{{'price.total' | trans}}</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% set totalCabine = 0 %}
                                    {% set subtotal = 0 %}
                                    {% set total = 0 %}
                                    {% set gratuity = 0 %}
                                    {% for item in orders %}

                                        {% if item.price > 0.0 %}
                                            {% set total = total + (item.priceUnit *  item.quantity ) %}
                                            {% set subtotal = subtotal + (item.priceUnit *  item.quantity ) %}
                                        {% else %}
                                            {% set gratuity = gratuity + (item.priceUnit *  item.quantity ) %}
                                            {% set subtotal = subtotal + (item.priceUnit *  item.quantity ) %}
                                        {% endif %}

                                        {% if item.idItem.idPresentation == "Cabine" or item.idItem.idPresentation == "Vente" %}
                                            {% set totalCabine = totalCabine + (item.price) %}
                                        {% endif %}

                                        <tr>
                                            <td class="product-name">
                                                <a href="{{ path('app_item_id', { 'id': item.idItem.id }) }}">{{ item.idItem.itemId }}</a>
                                            </td>
                                            <td class="product-designation ">
                                                <span class="text--category">
                                                    <a href="{{ path('app_item_id', { 'id': item.idItem.id }) }}">{{ item.idItem.labelFR }}</a>
                                                </span>
                                            </td>
                                            <td class="product-quantity">
                                                <span class="text--category show--mobile">  <a href="{{ path('app_item_id', { 'id': item.idItem.id }) }}">{{ item.idItem.labelFR }}</a></span>
                                                <div class="quantity">
                                                    <label>{{ 'quantity' | trans }}</label>
                                                    <input type="number" class="qty input-text js-update-item-quantity" step="1" min="1"
                                                        data-line="{{ item.id }}"
                                                        data-order="{{ order.id }}"
                                                        value="{{ item.quantity }}"
                                                        style="text-align: center;"
                                                    />
                                                    <div class="quantity-nav">
                                                        <div class="quantity-button quantity-up order-up" >+</div>
                                                        <div class="quantity-button quantity-down order-down">-</div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="product-quantityGroupage">
                                                <span class="text--category" id="qty_update_{{ item.idItem.id }}">{{ item.quantity }} x {{ item.quantityBundling }} </span>
                                            </td>
                                            <td class="product-priceUnit">
                                                <span class="text--category">  {{ item.priceUnit }} €</span>
                                            </td>
                                            <td class="product-priceTotal">
                                                <span class="text--category" id="price_update_{{ item.idItem.id }}">{{ item.price }} € </span>
                                            </td>
                                            <td>
                                                <a href="{{ path('app_order_product_edit_delete', {
                                                    'orderLineId': item.id,
                                                    'orderId': order.id,
                                                }) }}"><i class="icon icon-close"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <br />
                            <div>
                                <hr>
                                <p>{{ freeRestockingRules.getLabel(app.request.locale) }}</p>
                                <div class="search-wrapper" style="display:flex">
                                    <input class="js-global-search-term-promo" data-rules="{{ freeRestockingRules.valueCondition }}" type="text" style="outline:none"/>
                                    <button class="button button--primary-fill js-global-search-button-promo">
                                        {{ 'search.gratuity' | trans }}
                                    </button>
                                </div>
                                <div class="search-results-promo"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="cart--checkout-total">
                            <div class="cart--totals cart--totals-default">
                                <h3>{{'Cart' | trans}}</h3>

                                {% include('shop/_total.html.twig') %}

                                <div class="checkout-wrapper">
                                    <a href="{{ path("app_order_edit_publish", { 'id': order.id}) }}" class=" checkout button button--primary-fill">
                                        {{'Validate.order' | trans}}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/shop/promo.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'my_cart' | trans }}
{% endblock %}

{% block body %}

    <section class="section section--checkout">
        <div class="container">
            {% include 'flash_messages.html.twig' %}
            <form action="#" id="formPromo">
                <div class="row" id="clear">
                    <div class="col-12 col-md-8">
                        <div class="cart--checkout-table">
                            <table class="cart--table table-responsive">
                                <thead>
                                <tr>
                                    <th>{{'Product' | trans}}</th>
                                    <th>{{'Designation' | trans}}</th>
                                    <th>{{'quantity' | trans}}</th>
                                    <th>{{'Quantity.counts' | trans}}</th>
                                    <th>{{'price.unit' | trans}}</th>
                                    <th>{{'price.total' | trans}}</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody id="tbodyPromo">
                                {% set totalCabine = 0 %}
                                {% set total = 0 %}
                                {% for order in orders %}
                                    {% set total = total + (order.price *  order.quantity ) %}
                                    {% if  order.idItem.idPresentation == "Cabine" %}
                                        {% set totalCabine = totalCabine + (order.price) %}
                                    {% endif %}
                                    {% if order.priceOrder > 0 %}
                                        <tr>
                                            <td class="product-name">{{ order.idItem.id }}  </td>
                                            <td class="product-designation ">
                                                <span class="text--category">{{ order.idItem.labelFR }}</span>
                                            </td>
                                            <td class="product-quantity">
                                                <span class="text--category show--mobile"> {{ order.idItem.labelFR }}</span>
                                                <div class="quantity">
                                                    <label>{{ 'quantity' | trans }}</label>
                                                    <input type="number" data-promo="{{ order.promotionId.id }}" class="qty input-text js-update-cart-quantity-promo" step="1" min="1" data-product="{{ order.idItem.id }}" value="{{ order.quantity }}"
                                                           style="text-align: center;">
                                                    <div class="quantity-nav">
                                                        <div class="quantity-button quantity-up promo-up">+</div>
                                                        <div class="quantity-button quantity-down promo-down">-</div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="product-quantityGroupage">
                                                <span class="text--category" id="qty_update_{{ order.idItem.id }}">{{ order.quantity }} x {{ order.quantityBundling }} </span>
                                            </td>
                                            <td class="product-priceUnit">
                                                <span class="text--category">  {{ order.price }} €</span>
                                            </td>
                                            <td class="product-priceTotal">
                                                <span class="text--category" id="price_update_{{ order.idItem.id }}">{{ order.price *  order.quantity|round }} € </span>
                                            </td>
                                            <td>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td class="product-name">
                                            </td>
                                            <td class="product-designation ">
                                                <span class="text--category">{{ order.idItem.labelFR }}</span>
                                            </td>
                                            <td class="product">
                                                <span class="text--category show--mobile"> {{ order.idItem.labelFR }}</span>
                                                <div class="">
                                                    <span class="text--category">{{ order.quantity }}</span>

                                                </div>
                                            </td>
                                            <td class="">
                                                <span class="text--category">{{ order.quantity }} x {{ order.quantityBundling }} </span>
                                            </td>
                                            <td class="product-priceUnit">
                                                <span class="text--category">  {{ order.price }} €</span>
                                            </td>
                                            <td class="product-priceTotal">
                                                <span class="text--category">{{ order.price *  order.quantity|round }} € </span>
                                            </td>
                                            <td>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="cart--checkout-total">
                            <div class="cart--totals cart--totals-default">
                                <h3>{{'Cart' | trans}}</h3>
                                <table class="table-responsive cart--table-totals">
                                    <tbody>
                                    <tr class="cart-subtotal">
                                        <th>{{'Subtotal' | trans}}</th>
                                        <td></td>
                                    </tr>
                                    <tr class="order-total">
                                        <th>{{ 'Total'| trans }} </th>
                                        <td>
                                            <span class="price total" id="priceTotal">{{ total }} €</span>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="checkout-wrapper">
                                    <a href="{{ path("app_order_publish" , { 'promo': true}) }}" class=" checkout button button--primary-fill">
                                        {{'Validate.order' | trans}}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>

{% endblock %}

templates/shop/total.html.twig
<table class="table-responsive cart--table-totals">
    <tbody>
    <tr class="cart-subtotal">
        <th>{{ 'Subtotal' | trans }}</th>
        <td></td>
    </tr>
    <tr class="order-total">
        <th>{{ 'Total'| trans }} </th>
        <td>
            <span class="price total" id="priceTotal">{{ total }} €</span>
        </td>
    </tr>
    </tbody>
</table>