src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 * @UniqueEntity(fields={"idOrderX3"}, message="There is already exist")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $idOrder;

    /**
     *
     * @ORM\Column(type="integer", unique=true , nullable=true)
     */
    private $idOrderX3;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateOrder;

    /**
     * @ORM\Column(type="datetime" , nullable=true)
     */
    private $dateDelivery;

    /**
     * @ORM\Column(type="integer")
     */
    private $idStatut;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $idDownStatut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateLastDelivery;

    /**
     * @ORM\ManyToOne(targetEntity=Society::class, inversedBy="orders")
     */
    private $SocietyID;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $priceOrder;

    /**
     * @ORM\ManyToOne(targetEntity=CustomerIncoterm::class, inversedBy="orders")
     */
    private $incoterm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity=TransportMode::class)
     */
    private $transportMode;

    /**
     * @ORM\ManyToOne(targetEntity=Address::class)
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity=PaymentMethod::class)
     */
    private $paymentMethod;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comment;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdOrder(): ?int
    {
        return $this->idOrder;
    }

    public function setIdOrder(int $idOrder): self
    {
        $this->idOrder = $idOrder;
        return $this;
    }

    public function getIdOrderX3(): ?int
    {
        return $this->idOrderX3;
    }

    public function setIdOrderX3(int $idOrderX3): self
    {
        $this->idOrderX3 = $idOrderX3;
        return $this;
    }

    public function getDateOrder(): ?\DateTimeInterface
    {
        return $this->dateOrder;
    }

    public function setDateOrder(\DateTimeInterface $dateOrder): self
    {
        $this->dateOrder = $dateOrder;
        return $this;
    }

    public function getDateDelivery(): ?\DateTimeInterface
    {
        return $this->dateDelivery;
    }

    public function setDateDelivery(\DateTimeInterface $dateDelivery): self
    {
        $this->dateDelivery = $dateDelivery;
        return $this;
    }

    public function getIdStatut(): ?int
    {
        return $this->idStatut;
    }

    public function setIdStatut(int $idStatut): self
    {
        $this->idStatut = $idStatut;
        return $this;
    }

    public function getIdDownStatut(): ?int
    {
        return $this->idDownStatut;
    }

    public function setIdDownStatut(int $idDownStatut): self
    {
        $this->idDownStatut = $idDownStatut;
        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;
        return $this;
    }

    public function getDateLastDelivery(): ?\DateTimeInterface
    {
        return $this->dateLastDelivery;
    }

    public function setDateLastDelivery(?\DateTimeInterface $dateLastDelivery): self
    {
        $this->dateLastDelivery = $dateLastDelivery;
        return $this;
    }

    public function getSocietyID(): ?Society
    {
        return $this->SocietyID;
    }

    public function setSocietyID(?Society $SocietyID): self
    {
        $this->SocietyID = $SocietyID;
        return $this;
    }

    public function getPriceOrder(): ?float
    {
        return $this->priceOrder;
    }

    public function setPriceOrder(?float $priceOrder): self
    {
        $this->priceOrder = $priceOrder;

        return $this;
    }

    public function getIncoterm(): ?customerIncoterm
    {
        return $this->incoterm;
    }

    public function setIncoterm(?customerIncoterm $incoterm): self
    {
        $this->incoterm = $incoterm;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTransportMode(): ?TransportMode
    {
        return $this->transportMode;
    }

    public function setTransportMode(?TransportMode $transportMode): self
    {
        $this->transportMode = $transportMode;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPaymentMethod(): ?PaymentMethod
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(?PaymentMethod $paymentMethod): self
    {
        $this->paymentMethod = $paymentMethod;

        return $this;
    }

    public function getUniqueId()
    {
        return $this->getIdOrderX3();
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>{% block title %}Sothys{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block stylesheets %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
              integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp"
              crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/main.css') }} ">
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }} ">
    {% endblock %}
</head>

<body class="nav-fixed">
<header>
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-6 col-lg-2 col-xl-4">
                    <a class="logo" href="{{ path('app_home') }}">
                        <img
                            src="{{ asset('assets/images/logo-sothys.png') }}"
                            srcset="{{ asset('assets/images/logo-sothys.png') }}"
                            alt="Sothys"
                        />
                    </a>
                </div>
                {% if app.user != null %}
                    <div class="col-3 col-lg-5 col-xl-4">
                        <div class="search-wrapper" style="display:flex">
                            <input class="js-global-search-term" type="text" style="outline:none" />
                            <button class="button button--primary-fill js-global-search-button">
                                {{ 'search.global' | trans}}
                            </button>
                        </div>
                        <div class="search-results"></div>
                    </div>
                    <div class="col-3 col-lg-5 col-xl-4">
                            <div class="navbar-tools">
                                <ul class="list--horizontal">
                                    <li>
                                        <a href="{{ path('app_shop') }}" aria-label="{{ 'access_my_cart' | trans }}"
                                            title="{{ 'access_my_cart' | trans }}" data-microtip-position="bottom" role="tooltip"
                                            class="cart__access js-cart-toggler"
                                        >
                                            <i class="icon icon-panier">
                                                <span class="hidden">{{ 'my_cart' | trans }}</span>
                                            </i>
                                            <span id="cartItem">{{ cartItem|default('0') }}</span>
                                        </a>
                                    </li>
                                    <li class="account__access_button d-none d-lg-block">
                                        <a
                                            href="{{ path('app_login') }}" aria-label="{{ 'access_my_account' | trans }}"
                                            title="{{ 'access_my_account' | trans }}"
                                            style="display: flex"
                                        >
                                            <i class="icon icon-compte">
                                                <span class="hidden">{{ 'my_account' | trans }}</span>
                                            </i>
                                            <span style="font-size:1.5rem">{{ app.user.email }}</span>
                                        </a>
                                        <div class="account__access_wrapper">
                                            <div class="account__access_inner">
                                                <a href="{{ path('app_account') }}" class="button button--small button--dark" title="{{ 'my_account' | trans }}">
                                                    {{ 'my_account' | trans }}
                                                </a>
                                                <a href="{{ path('app_logout') }}" class="button button--small button--dark" title="{{ 'logout' | trans }}">
                                                    {{ 'logout' | trans }}
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% if app.user != null %}
        <div class="header__nav">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="navbar navbar--fixed js-navbar">
                            <div class="navbar__wrapper">
                                <div class="navbar__collapse">
                                    <div class="d-flex d-lg-none navbar__header">
                                        <button class="navbar__toggler js-navbar-toggler">
                                            <i class="icon icon-close">
                                                <span class="hidden">fermer</span>
                                            </i>
                                        </button>
                                        <ul class="lang">
                                            <li>
                                                <a href="#" title="Choix de la langue en Francais" class="active">FR</a>
                                            </li>
                                            <li>
                                                <a href="#" title="Choix de la langue en Anglais">EN</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <ul class="navbar__menu navbar__menu--desktop">
                                        <li class="menu-item">
                                            <a href="{{ path('app_home') }}" class="{% if app.request.attributes.get('_route') starts with 'app_home' %} e-shop{% endif %}">
                                                {{ 'homePage' | trans }}
                                            </a>
                                        </li>
                                        <li class="menu-item menu-item--has-child">
                                            <a class="{% if app.request.attributes.get('_route') starts with 'app_gamme' or app.request.attributes.get('_route') starts with 'app_item_id' %} e-shop {% endif %}">{{ 'products' | trans }}</a>
                                            <div class="menu-item__submenu">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <ul class="menu-item__submenu--large">
                                                                {% for gamme in categories.getProductGamme(app.user.societyID) %}
                                                                    <li class="menu-item__submenu-item">
                                                                        <a href="{{ path('app_gamme', {
                                                                            gamme_id: gamme.id,
                                                                            type : 'vente'
                                                                        }) }}" class="nav-link">
                                                                            {{ gamme.getLabel(app.request.locale) }}
                                                                        </a>
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="menu-item menu-item--has-child">
                                            <a class="{% if app.request.attributes.get('_route') starts with 'app_gamme'  or app.request.attributes.get('_route') starts with 'app_item_id' %} e-shop {% endif %}">PLV</a>
                                            <div class="menu-item__submenu">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <ul class="menu-item__submenu--large">
                                                                {% for gamme in categories.getPLVGamme(app.user.societyID) %}
                                                                    <li class="menu-item__submenu-item">
                                                                        <a href="{{ path('app_gamme', {
                                                                            gamme_id: gamme.id,
                                                                            type : 'plv'
                                                                        }) }}" class="nav-link">
                                                                            {{ gamme.getLabel(app.request.locale) }}
                                                                        </a>
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="menu-item">
                                            <a href="{{ path('app_order') }}" class="{% if app.request.attributes.get('_route') starts with 'app_order' %} e-shop{% endif %}">
                                                {{ 'my.orders' | trans }}
                                            </a>
                                        </li>
                                        <li class="menu-item">
                                            <a class="{% if app.request.attributes.get('_route') starts with 'app_promo' %} e-shop{% endif %}" href="{{ path('app_home') }}">
                                                {{ 'my_promotion' | trans }}
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</header>
{% block body %}
{% endblock %}

{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ asset('assets/js/app.js') }}"></script>
{% endblock %}
<div class="up-button" style="display: block;"><i class="fas fa-chevron-up"></i></div>
</body>
</html>

templates/base_pdf.html.twig
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        {% block body %}
        {% endblock body %}
    </body>
</html>

templates/flash_messages.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="flash-{{ label }} alert-{{ label }}">
            {{ message }}
        </div>
    {% endfor %}
{% endfor %}